<?php
/**
 * @author Ondrej Donek <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-sendlane_plugin for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-sendlane_plugin
 * @see SP_Dashboard_Widget::config()
 * @since 1.0.0
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * @var integer $number
 */
$number = int_val( filter_input( INPUT_POST, 'number' ) );

// Updates widget options
self::update_dashboard_widget_options( SP_Dashboard_Widget::WID, self::get_default_options() );

?>
<input type="text" name="number" value="<?php echo $value ?>">
