<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-sendlane_plugin for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-sendlane_plugin
 * @see odwpSendlanePlugin::render_admin_page_add()
 * @since 1.0.0
 *
 * @todo Add `wpnonce` for the security!
 * @todo Argument "child_of" for {@see get_pages()} and {@see get_posts()} should be set by user options!
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/** @var array $avail_lists Available lists defined in Sendlane application. */
$avail_lists = odwpSendlanePlugin::get_lists();
/** @var array $avail_tags Available tags defined in Sendlane application. */
$avail_tags  = odwpSendlanePlugin::get_tags();
/** @var boolean $api_error TRUE if API error occured. */
$api_error   = array_key_exists( 'error', $avail_lists ) || array_key_exists( 'error', $avail_tags );


if( ! function_exists( 'odwpsp_print_options_errors' ) ) :
    /**
     * @internal Prints errors in Sendlane tags/lists return data.
     * @param array $list
     * @return void
     * @since 1.0.0
     */
    function odwpsp_print_options_errors( array $list ) {
        /** @var string $msg Basic API error message. */
        $msg = __( '<b>Chyba Sendlane API:</b>&nbsp;%s', 'odwp-sendlane_plugin' );

        if( ! array_key_exists( 'error', $list ) ) {
            return;
        }

        foreach( $list['error'] as $err ) {
            odwpSendlanePlugin::print_notice( sprintf( $msg, $err ), 'error', false );
        }
    }
endif;

?>
<div class="wrap">
    <h1><?php _e( 'Přidat akci', 'odwp-sendlane_plugin' ) ?></h1>
    <?php odwpsp_print_options_errors( $avail_lists ) ?>
    <?php odwpsp_print_options_errors( $avail_tags ) ?>
    <p><?php printf( __( 'Zde můžete přidat akci dle %sSendlane API%s, která se má provést na vybrané stránce. Volitelně můžete přidat <code>GET</code> nebo <code>POST</code> parametr, který bude ke spuštění akce také vyžadovaný.', 'odwp-sendlane_plugin' ), '<a href="http://help.sendlane.com/knowledgebase/api-docs/" target="_blank">', '</a>' ) ?></p>
    <form method="post" action="<?php echo admin_url( '?page=odwpsp_menu_add' ) ?>" novalidate="novalidate">
        <input type="hidden" name="_wpnonce" value="">
        <table class="form-table">
            <tbody>
                <tr>
                    <th scope="row">
                        <label for="odwpsp-page"><?php _e( 'Cílová stránka', 'odwp-sendlane_plugin' ) ?></label>
                    </th>
                    <td>
                        <?php wp_dropdown_pages( [
                            'id'    => 'odwpsp-page',
                            'name'  => 'page',
                            'echo'  => true,
                            'class' => 'odwpsp-page_select',
                        ] ) ?>
                        <p class="description"><?php _e( 'Vyberte cílovou stránku.', 'odwp-sendlane_plugin' ) ?></p>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <label for="odwpsp-action"><?php _e( 'Akce', 'odwp-sendlane_plugin' ) ?></label>
                    </th>
                    <td>
                        <select id="odwpsp-action" name="action">
                            <option value="subscribe"><?php _e( 'Přihlásit', 'odwp-sendlane_plugin' ) ?></option>
                            <option value="unsubscribe"><?php _e( 'Odhlásit', 'odwp-sendlane_plugin' ) ?></option>
                            <option value="tag_add"><?php _e( 'Přidat tag', 'odwp-sendlane_plugin' ) ?></option>
                            <option value="tag_remove"><?php _e( 'Odebrat tag', 'odwp-sendlane_plugin' ) ?></option>
                        </select>
                        <p class="description"><?php _e( 'Akce k provedení přes Sendlane API', 'odwp-sendlane_plugin' ) ?></p>
                    </td>
                </tr>
                <tr id="odwpsp-lists_row">
                    <th scope="row">
                        <label for="odwpsp-lists"><?php _e( 'Seznam', 'odwp-sendlane_plugin' ) ?></label>
                    </th>
                    <td>
                        <?php if( $api_error === true ) : ?>
                        <select id="odwpsp-lists" name="lists" disabled="disabled"></select>
                        <p class="description" style="color: #f30;"><?php _e( 'Nastala chyba při získávání dat prostřednictvím <b>Sendlane API</b>!', 'odwp-sendlane_plugin' ) ?></p>
                        <?php else : ?>
                        <select id="odwpsp-lists" name="lists">
                            <?php foreach( $avail_lists as $list ) : ?>
                            <option value="<?php echo $list['list_id'] ?>"><?php echo $list['list_name'] ?></option>
                            <?php endforeach ?>
                        </select>
                        <?php endif ?>
                    </td>
                </tr>
                <tr id="odwpsp-tags_row">
                    <th scope="row">
                        <label for="odwpsp-tags"><?php _e( 'Tag', 'odwp-sendlane_plugin' ) ?></label>
                    </th>
                    <td>
                        <?php if( $api_error === true ) : ?>
                        <select id="odwpsp-tags" name="tags" disabled="disabled"></select>
                        <p class="description" style="color: #f30;"><?php _e( 'Nastala chyba při získávání dat prostřednictvím <b>Sendlane API</b>!', 'odwp-sendlane_plugin' ) ?></p>
                        <?php else : ?>
                        <select id="odwpsp-tags" name="tags">
                            <?php foreach( $avail_tags as $tag ) : ?>
                            <option value="<?php echo $tag['tag_id'] ?>"><?php echo $tag['tag_name'] ?></option>
                            <?php endforeach ?>
                        </select>
                        <?php endif ?>
                    </td>
                </tr>
            </tbody>
        </table>
        <p class="submit">
            <input type="submit" name="submit" id="submit" class="button button-primary" value="<?php _e( 'Přidat akci', 'odwp-sendlane_plugin' ) ?>">&nbsp;
            <input type="reset" name="reset" id="reset" class="button button-cancel" value="<?php _e( 'Zrušit', 'odwp-sendlane_plugin' ) ?>">
        </p>
    </form>
</div>
