<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-sendlane_plugin for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-sendlane_plugin
 * @see odwpSendlanePlugin::render_admin_page_add()
 * @since 1.0.0
 *
 * @todo Add `wpnonce` for the security!
 * @todo Argument "child_of" for {@see get_pages()} and {@see get_posts()} should be set by user options!
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/** @var array $avail_lists Available lists defined in Sendlane application. */
$avail_lists = odwpSendlanePlugin::get_lists();
/** @var array $avail_tags Available tags defined in Sendlane application. */
$avail_tags  = odwpSendlanePlugin::get_tags();
/** @var boolean $api_error TRUE if API error occured. */
$api_error   = array_key_exists( 'error', $avail_lists ) || array_key_exists( 'error', $avail_tags );


if( ! function_exists( 'odwpsp_print_options_errors' ) ) :
    /**
     * @internal Prints errors in Sendlane tags/lists return data.
     * @param array $list
     * @return void
     * @since 1.0.0
     */
    function odwpsp_print_options_errors( array $list ) {
        /** @var string $msg Basic API error message. */
        $msg = __( '<b>Chyba Sendlane API:</b>&nbsp;%s', 'odwp-sendlane_plugin' );

        if( ! array_key_exists( 'error', $list ) ) {
            return;
        }

        foreach( $list['error'] as $err ) {
            odwpSendlanePlugin::print_notice( sprintf( $msg, $err ), 'error', false );
        }
    }
endif;

?>
<div class="wrap">
    <h1><?php _e( 'Přidat akci', 'odwp-sendlane_plugin' ) ?></h1>
    <?php odwpsp_print_options_errors( $avail_lists ) ?>
    <?php odwpsp_print_options_errors( $avail_tags ) ?>
    <!-- TODO Přesunout do screen help tabu!!! -->
    <p><?php printf( __( 'Zde můžete přidat akci dle <a href="%1$s" target="_blank">Sendlane API</a>, která se má provést na vybrané stránce. Volitelně můžete přidat <code>GET</code> nebo <code>POST</code> parametr, který bude ke spuštění akce také vyžadovaný &ndash; odeslání těchto parametrů můžete dosáhnout pomocí formulářů či (v případě <code>GET</code> dotazů) pouhých odkazů &ndash; ty můžete vytvořit standardními <a href="%2$s" target="_blank">WordPress</a> prostředky či prostřednictvím pluginů. U některých akcí <a href="%1$s" target_blank">Sendlane API</a> je to dokonce povinné.', 'odwp-sendlane_plugin' ), 'http://help.sendlane.com/knowledgebase/api-docs/', 'https://wordpress.org/' ) ?></p>
    <!-- // TODO Přesunout do screen help tabu!!! -->
    <form method="post" action="<?php echo admin_url( '?page=odwpsp_menu_add' ) ?>" novalidate="novalidate">
        <input type="hidden" name="_wpnonce" value="">
        <table class="form-table">
            <tbody>
                <tr>
                    <th scope="row">
                        <label for="odwpsp-page"><?php _e( 'Stránka', 'odwp-sendlane_plugin' ) ?></label>
                    </th>
                    <td>
                        <?php wp_dropdown_pages( [
                            'id'    => 'odwpsp-page',
                            'name'  => 'page',
                            'echo'  => true,
                            'class' => 'odwpsp-page_select',
                        ] ) ?>
                        <p class="description"><?php printf( __( 'Vyberte cílovou stránku - stránka při jejímž načtení se má <a href="%s" target="_blank">Sendlane API</a> akce spustit.', 'odwp-sendlane_plugin' ), 'http://help.sendlane.com/knowledgebase/api-docs/' ) ?></p>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <label for="odwpsp-action"><?php _e( 'Akce', 'odwp-sendlane_plugin' ) ?></label>
                    </th>
                    <td>
                        <select id="odwpsp-action" name="action">
                            <!--<option value="subscribe"><?php _e( 'Přihlásit', 'odwp-sendlane_plugin' ) ?></option>
                            <option value="unsubscribe"><?php _e( 'Odhlásit', 'odwp-sendlane_plugin' ) ?></option>
                            <option value="tag_add"><?php _e( 'Přidat tag', 'odwp-sendlane_plugin' ) ?></option>
                            <option value="tag_remove"><?php _e( 'Odebrat tag', 'odwp-sendlane_plugin' ) ?></option>-->
                            <?php
                            $calls = new Sendlane_Api_Calls();
                            foreach( $calls as $call_key => $call ) : ?>
                            <option value="<?php echo  $call->get_name() ?>"><?php echo  $call->get_name() ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="description"><?php printf( __( 'Vyberte jednu z akcí <a href="%s" target="_blank">Sendlane API</a>, kterou chcete spustit na této stránce &ndash; pokud by jste náhodou chtěli na té samé stránce spustit více akcí, stačí novou akci definovat pomocí formuláře a zvolit stejnou stránku. Zvolit můžete jen některé z dostupných akcí a ke všem jsou připojeny základní parametry (<code>api_key</code> a <code>hash_key</code>).', 'odwp-sendlane_api' ), null ) ?></p>
                    </td>
                </tr>
            </tbody>
        </table>
        <!-- TODO -->
        <p style="color: #f30; font-weight: bold; margin: 0;">V praxi by se toto mělo zobrazovat až po vybrání akce a také by se mělo kontrolovat, zda jsou data načtená či ne.</p>
        <ul style="color: #f30; font-weight: bold; list-style: square; margin: 0 0 0 1em;">
            <li>přes <em>AJAX</em> zobrazovat detaily o daném volání (popis a parametry)</li>
            <li>přes <em>AJAX</em> nastavit zbytek formuláře dle vybraného volání</li>
            <li>uložit formulář</li>
        </ul>
        <!-- //TODO -->
        <div id="odwpsp-additional_action_settings">
            <h2><?php _e( 'Dodatečné nastavení akce', 'odwp-sendlane_plugin' ) ?></h2>
            <table class="form-table">
                <tbody id="odwpsp-action_parameters_tbody">
                    <tr class="odwpsp-lists_row">
                        <th scope="row">
                            <label for="odwpsp-lists"><?php _e( 'Seznam', 'odwp-sendlane_plugin' ) ?></label>
                        </th>
                        <td>
                            <?php if( $api_error === true ) : ?>
                            <select id="odwpsp-lists" name="lists" disabled="disabled"></select>
                            <p class="description" style="color: #f30;"><?php _e( 'Nastala chyba při získávání dat prostřednictvím <b>Sendlane API</b>!', 'odwp-sendlane_plugin' ) ?></p>
                            <?php else : ?>
                            <select id="odwpsp-lists" name="lists">
                                <?php foreach( $avail_lists as $list ) : ?>
                                <option value="<?php echo $list['list_id'] ?>"><?php echo $list['list_name'] ?></option>
                                <?php endforeach ?>
                            </select>
                            <?php endif ?>
                        </td>
                    </tr>
                    <tr class="odwpsp-tags_row">
                        <th scope="row">
                            <label for="odwpsp-tags"><?php _e( 'Tag', 'odwp-sendlane_plugin' ) ?></label>
                        </th>
                        <td>
                            <?php if( $api_error === true ) : ?>
                            <select id="odwpsp-tags" name="tags" disabled="disabled"></select>
                            <p class="description" style="color: #f30;"><?php _e( 'Nastala chyba při získávání dat prostřednictvím <b>Sendlane API</b>!', 'odwp-sendlane_plugin' ) ?></p>
                            <?php else : ?>
                            <select id="odwpsp-tags" name="tags">
                                <?php foreach( $avail_tags as $tag ) : ?>
                                <option value="<?php echo $tag['tag_id'] ?>"><?php echo $tag['tag_name'] ?></option>
                                <?php endforeach ?>
                            </select>
                            <?php endif ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <p class="submit">
            <input type="submit" name="submit" id="submit" class="button button-primary" value="<?php _e( 'Přidat akci', 'odwp-sendlane_plugin' ) ?>">&nbsp;
            <input type="reset" name="reset" id="reset" class="button button-cancel" value="<?php _e( 'Zrušit', 'odwp-sendlane_plugin' ) ?>">
        </p>
    </form>
</div>
