<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-sendlane_plugin for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-sendlane_plugin
 * @see odwpSendlanePlugin::render_admin_page_list()
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<div class="wrap">
    <h1><?php _e( 'Nastavení pro Sendlane plugin', 'odwp-sendlane_plugin' ) ?></h1>
    <form action="options.php" method="post"><?php
        settings_fields( odwpSendlanePlugin::SLUG );
        do_settings_sections( odwpSendlanePlugin::SLUG );
        submit_button();
    ?></form>
</div>
