<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-sendlane_plugin for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-sendlane_plugin
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

$avail_pages = get_pages( [
    'sort_order'   => 'asc',
    'hierarchical' => 0,
    'child_of'     => 0,
    'post_type'    => 'page',
] );
$avail_lists = odwpSendlanePlugin::get_lists();
$avail_tags  = odwpSendlanePlugin::get_tags();
$api_error   = array_key_exists( 'error', $avail_lists ) || array_key_exists( 'error', $avail_tags );

?>
<div class="wrap">
    <h1><?php _e( 'Přidat akci', 'odwp-sendlane_plugin' ) ?></h1>
    <?php if( array_key_exists( 'error', $avail_lists ) ) : 
    foreach( $avail_lists['error'] as $msg) : 
        odwpSendlanePlugin::print_error( __( '<b>Chyba Sendlane API:</b>&nbsp;', 'odwp-sendlane_plugin' ) . $msg, 'error' );
    endforeach; 
    endif; ?>
    <?php if( array_key_exists( 'error', $avail_tags ) ) : 
    foreach( $avail_tags['error'] as $msg) : 
        odwpSendlanePlugin::print_error( __( '<b>Chyba Sendlane API:</b>&nbsp;', 'odwp-sendlane_plugin' ) . $msg, 'error' );
    endforeach; 
    endif; ?>
    <form method="post" action="<?php echo admin_url( '?page=odwpsp_menu_add' ) ?>" novalidate="novalidate">
        <input type="hidden" name="_wpnonce" value="">
        <table class="form-table">
            <tbody>
                <tr>
                    <th scope="row">
                        <label for="odwpsp-page"><?php _e( 'Cílová stránka', 'odwp-sendlane_plugin' ) ?></label>
                    </th>
                    <td>
                        <select id="odwpsp-page" name="page">
                            <?php foreach( $avail_pages as $page ) : ?>
                            <option value="<?php echo $page->ID ?>"><?php echo $page->post_title ?></option>
                            <?php endforeach ?>
                        </select>
                        <p class="description"><?php _e( 'Vyberte cílovou stránku.', 'odwp-sendlane_plugin' ) ?></p>
                    </td>
                </tr>
                <tr>
                    <th scope="row">
                        <label for="odwpsp-action"><?php _e( 'Akce', 'odwp-sendlane_plugin' ) ?></label>
                    </th>
                    <td>
                        <select id="odwpsp-action" name="action">
                            <option value="subscribe"><?php _e( 'Přihlásit', 'odwp-sendlane_plugin' ) ?></option>
                            <option value="unsubscribe"><?php _e( 'Odhlásit', 'odwp-sendlane_plugin' ) ?></option>
                            <option value="tag_add"><?php _e( 'Přidat tag', 'odwp-sendlane_plugin' ) ?></option>
                            <option value="tag_remove"><?php _e( 'Odebrat tag', 'odwp-sendlane_plugin' ) ?></option>
                        </select>
                        <p class="description"><?php _e( 'Akce k provedení přes Sendlane API', 'odwp-sendlane_plugin' ) ?></p>
                    </td>
                </tr>
                <tr id="odwpsp-lists_row">
                    <th scope="row">
                        <label for="odwpsp-lists"><?php _e( 'Seznam', 'odwp-sendlane_plugin' ) ?></label>
                    </th>
                    <td>
                        <?php if( $api_error === true ) : ?>
                        <select id="odwpsp-lists" name="lists" disabled="disabled"></select>
                        <p class="description" style="color: #f30;"><?php _e( 'Nastala chyba při získávání dat prostřednictvím <b>Sendlane API</b>!', 'odwp-sendlane_plugin' ) ?></p>
                        <?php else : ?>
                        <select id="odwpsp-lists" name="lists">
                            <?php foreach( $avail_lists as $list ) : ?>
                            <option value="<?php echo $list['list_id'] ?>"><?php echo $list['list_name'] ?></option>
                            <?php endforeach ?>
                        </select>
                        <?php endif ?>
                    </td>
                </tr>
                <tr id="odwpsp-tags_row">
                    <th scope="row">
                        <label for="odwpsp-tags"><?php _e( 'Tag', 'odwp-sendlane_plugin' ) ?></label>
                    </th>
                    <td>
                        <?php if( $api_error === true ) : ?>
                        <select id="odwpsp-tags" name="tags" disabled="disabled"></select>
                        <p class="description" style="color: #f30;"><?php _e( 'Nastala chyba při získávání dat prostřednictvím <b>Sendlane API</b>!', 'odwp-sendlane_plugin' ) ?></p>
                        <?php else : ?>
                        <select id="odwpsp-tags" name="tags">
                            <?php foreach( $avail_tags as $tag ) : ?>
                            <option value="<?php echo $tag['tag_id'] ?>"><?php echo $tag['tag_name'] ?></option>
                            <?php endforeach ?>
                        </select>
                        <?php endif ?>
                    </td>
                </tr>
            </tbody>
        </table>
        <p class="submit">
            <input type="submit" name="submit" id="submit" class="button button-primary" value="<?php _e( 'Přidat akci', 'odwp-sendlane_plugin' ) ?>">&nbsp;
            <input type="reset" name="reset" id="reset" class="button button-cancel" value="<?php _e( 'Zrušit', 'odwp-sendlane_plugin' ) ?>">
        </p>
    </form>
</div>
