<?php
/**
 * @author Ondrej Donek <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-sendlane_plugin for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-sendlane_plugin
 * @see SP_Plugin::render_setting_domain()
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * @var array $options Options of the Sendlane Plugin.
 */
$options = SP_Plugin::get_options();

?>
<input type="text" name="odwpsp_settings[domain]" value="<?php echo $options['domain'] ?>" class="regular-text">
